// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calc_ssr
SEXP calc_ssr(arma::Mat<double> r, arma::Mat<double> s, Rcpp::List eqs);
RcppExport SEXP nlsur_calc_ssr(SEXP rSEXP, SEXP sSEXP, SEXP eqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type s(sSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type eqs(eqsSEXP);
    __result = Rcpp::wrap(calc_ssr(r, s, eqs));
    return __result;
END_RCPP
}
// arma_reshape
arma::Mat<double> arma_reshape(arma::Mat<double> mm, int sizetheta);
RcppExport SEXP nlsur_arma_reshape(SEXP mmSEXP, SEXP sizethetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< int >::type sizetheta(sizethetaSEXP);
    __result = Rcpp::wrap(arma_reshape(mm, sizetheta));
    return __result;
END_RCPP
}
// calc_reg
SEXP calc_reg(arma::Mat<double> x, arma::Mat<double> r, arma::Mat<double> qS, int sizetheta, int neqs);
RcppExport SEXP nlsur_calc_reg(SEXP xSEXP, SEXP rSEXP, SEXP qSSEXP, SEXP sizethetaSEXP, SEXP neqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type qS(qSSEXP);
    Rcpp::traits::input_parameter< int >::type sizetheta(sizethetaSEXP);
    Rcpp::traits::input_parameter< int >::type neqs(neqsSEXP);
    __result = Rcpp::wrap(calc_reg(x, r, qS, sizetheta, neqs));
    return __result;
END_RCPP
}
// arma_solve
SEXP arma_solve(arma::Mat<double> m1, arma::Mat<double> m2);
RcppExport SEXP nlsur_arma_solve(SEXP m1SEXP, SEXP m2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type m2(m2SEXP);
    __result = Rcpp::wrap(arma_solve(m1, m2));
    return __result;
END_RCPP
}
