// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ssr_est
SEXP ssr_est(arma::Mat<double> r, arma::Mat<double> s, arma::Col<double> w);
RcppExport SEXP _nlsur_ssr_est(SEXP rSEXP, SEXP sSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(ssr_est(r, s, w));
    return rcpp_result_gen;
END_RCPP
}
// arma_reshape
arma::Mat<double> arma_reshape(arma::Mat<double> mm, int sizetheta);
RcppExport SEXP _nlsur_arma_reshape(SEXP mmSEXP, SEXP sizethetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< int >::type sizetheta(sizethetaSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_reshape(mm, sizetheta));
    return rcpp_result_gen;
END_RCPP
}
// wls_est
SEXP wls_est(arma::Mat<double> x, arma::Mat<double> r, arma::Mat<double> qS, arma::Col<double> w, int sizetheta, bool fullreg, double tol);
RcppExport SEXP _nlsur_wls_est(SEXP xSEXP, SEXP rSEXP, SEXP qSSEXP, SEXP wSEXP, SEXP sizethetaSEXP, SEXP fullregSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type qS(qSSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type sizetheta(sizethetaSEXP);
    Rcpp::traits::input_parameter< bool >::type fullreg(fullregSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(wls_est(x, r, qS, w, sizetheta, fullreg, tol));
    return rcpp_result_gen;
END_RCPP
}
// wt_mean
SEXP wt_mean(arma::Col<double>& x, arma::Col<double>& w);
RcppExport SEXP _nlsur_wt_mean(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<double>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::Col<double>& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(wt_mean(x, w));
    return rcpp_result_gen;
END_RCPP
}
// cov_robust
SEXP cov_robust(arma::Mat<double> x, arma::Mat<double> u, arma::Mat<double> qS, arma::Col<double> w, int sizetheta);
RcppExport SEXP _nlsur_cov_robust(SEXP xSEXP, SEXP uSEXP, SEXP qSSEXP, SEXP wSEXP, SEXP sizethetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type qS(qSSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type sizetheta(sizethetaSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_robust(x, u, qS, w, sizetheta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nlsur_ssr_est", (DL_FUNC) &_nlsur_ssr_est, 3},
    {"_nlsur_arma_reshape", (DL_FUNC) &_nlsur_arma_reshape, 2},
    {"_nlsur_wls_est", (DL_FUNC) &_nlsur_wls_est, 7},
    {"_nlsur_wt_mean", (DL_FUNC) &_nlsur_wt_mean, 2},
    {"_nlsur_cov_robust", (DL_FUNC) &_nlsur_cov_robust, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_nlsur(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
