# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ssr_est
#' @description calculate SSR where
#' \eqn{SSR(\beta) = u'D'Du.}
#' @param r residuals
#' @param s weighting matrix
#' @param w vector of weights
#' @export
ssr_est <- function(r, s, w) {
    .Call(`_nlsur_ssr_est`, r, s, w)
}

#' arma_reshape
#' @param mm a matrix
#' @param sizetheta integer of length(theta) to shrink mm into
#' @description reshape mm for blockwise multiplication
#' @examples
#' mm <- matrix(c(11,21,31,41,
#'  12,22,32,42,
#'  13,23,33,43,
#'  14,24,34,44),
#'  ncol = 4)
#'
#' mm_a <- arma_reshape(mm, 2)
#'
#' mm_m <- matrix(t(mm), nrow = 2, byrow =T )
#' @export
arma_reshape <- function(mm, sizetheta) {
    .Call(`_nlsur_arma_reshape`, mm, sizetheta)
}

#' wls_est
#' @param x matrix of derivatives
#' @param r residual matrix
#' @param qS weighting matrix of sizetheta x sizetheta
#' @param w vector of weights
#' @param sizetheta integer defining the amount of coefficients
#' @param fullreg bool defining if WLS or Cov is calculated
#' @param tol tolerance used for qr()
#' @description as reference see:
#' http://www.navipedia.net/index.php/Block-Wise_Weighted_Least_Square
#' @export
wls_est <- function(x, r, qS, w, sizetheta, fullreg, tol) {
    .Call(`_nlsur_wls_est`, x, r, qS, w, sizetheta, fullreg, tol)
}

#' wt_mean
#' @param x matrix of derivatives
#' @param w vector of weights
#' @export
wt_mean <- function(x, w) {
    .Call(`_nlsur_wt_mean`, x, w)
}

#' cov_robust
#'
#' @param x matrix of derivatives
#' @param u u
#' @param qS weighting matrix
#' @param w vector of weights
#' @param sizetheta sizetheta
#' @description As discussed in Wooldridge (2002, 160)
#' @export
cov_robust <- function(x, u, qS, w, sizetheta) {
    .Call(`_nlsur_cov_robust`, x, u, qS, w, sizetheta)
}

