# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_ssr <- function(r, s, eqs) {
    .Call('nlsur_calc_ssr', PACKAGE = 'nlsur', r, s, eqs)
}

calc_reg <- function(x, r, qS, sizetheta, eqns) {
    .Call('nlsur_calc_reg', PACKAGE = 'nlsur', x, r, qS, sizetheta, eqns)
}

