# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_ssr <- function(r, s, neqs) {
    .Call('nlsur_calc_ssr', PACKAGE = 'nlsur', r, s, neqs)
}

arma_reshape <- function(mm, sizetheta) {
    .Call('nlsur_arma_reshape', PACKAGE = 'nlsur', mm, sizetheta)
}

calc_reg <- function(x, r, qS, sizetheta, neqs, fullreg) {
    .Call('nlsur_calc_reg', PACKAGE = 'nlsur', x, r, qS, sizetheta, neqs, fullreg)
}

